export const LOGIN_DENTIST_REQUEST = "LOGIN_DENTIST_REQUEST";
export const LOGIN_DENTIST_ERROR = "LOGIN_DENTIST_ERROR";
export const LOGIN_DENTIST_SUCCESS = "LOGIN_DENTIST_SUCCESS";

export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const REGISTER_PATIENT_REQUEST = "REGISTER_PATIENT_REQUEST";
export const REGISTER_PATIENT_ERROR = "REGISTER_PATIENT_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_DENTIST_SUCCESS = "REGISTER_DENTIST_SUCCESS";
export const REGISTER_DENTIST_ERROR = "REGISTER_DENTIST_ERROR";
export const REGISTER_DENTIST_REQUEST = "REGISTER_DENTIST_REQUEST";

export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const EDIT_PATIENT_SUCCESS = "EDIT_PATIENT_SUCCESS";
export const EDIT_PATIENT_ERROR = "EDIT_PATIENT_ERROR";
export const EDIT_PATIENT_REQUEST = "EDIT_PATIENT_REQUEST";

export const EDIT_DENTIST_SUCCESS = "EDIT_DENTIST_SUCCESS";
export const EDIT_DENTIST_ERROR = "EDIT_DENTIST_ERROR";
export const EDIT_DENTIST_REQUEST = "EDIT_DENTIST_REQUEST";

export const EDIT_ADMIN_SUCCESS = "EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_ERROR = "EDIT_ADMIN_ERROR";
export const EDIT_ADMIN_REQUEST = "EDIT_ADMIN_REQUEST";

export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";

export const GET_DENTIST_ERROR = "GET_DENTIST_ERROR";
export const GET_DENTIST_REQUEST = "GET_DENTIST_REQUEST";
export const GET_DENTIST_SUCCESS = "GET_DENTIST_SUCCESS";

export const GET_ADMIN_ERROR = "GET_ADMIN_ERROR";
export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";

export const GET_DENTIST_PROFILE_ERROR = "GET_DENTIST_PROFILE_ERROR";
export const GET_DENTIST_PROFILE_REQUEST = "GET_DENTIST_PROFILE_REQUEST";
export const GET_DENTIST_PROFILE_SUCCESS = "GET_DENTIST_PROFILE_SUCCESS";

export const GET_PATIENT_PROFILE_ERROR = "GET_PATIENT_PROFILE_ERROR";
export const GET_PATIENT_PROFILE_REQUEST = "GET_PATIENT_PROFILE_REQUEST";
export const GET_PATIENT_PROFILE_SUCCESS = "GET_PATIENT_PROFILE_SUCCESS";