export const LOGIN_DENTIST_REQUEST = "LOGIN_DENTIST_REQUEST";
export const LOGIN_DENTIST_ERROR = "LOGIN_DENTIST_ERROR";
export const LOGIN_DENTIST_SUCCESS = "LOGIN_DENTIST_SUCCESS";

export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const REGISTER_PATIENT_REQUEST = "REGISTER_PATIENT_REQUEST";
export const REGISTER_PATIENT_ERROR = "REGISTER_PATIENT_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_DENTIST_SUCCESS = "REGISTER_DENTIST_SUCCESS";
export const REGISTER_DENTIST_ERROR = "REGISTER_DENTIST_ERROR";
export const REGISTER_DENTIST_REQUEST = "REGISTER_DENTIST_REQUEST";

export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const EDIT_PATIENT_SUCCESS = "EDIT_PATIENT_SUCCESS";
export const EDIT_PATIENT_ERROR = "EDIT_PATIENT_ERROR";
export const EDIT_PATIENT_REQUEST = "EDIT_PATIENT_REQUEST";

export const EDIT_DENTIST_SUCCESS = "EDIT_DENTIST_SUCCESS";
export const EDIT_DENTIST_ERROR = "EDIT_DENTIST_ERROR";
export const EDIT_DENTIST_REQUEST = "EDIT_DENTIST_REQUEST";

export const EDIT_ADMIN_SUCCESS = "EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_ERROR = "EDIT_ADMIN_ERROR";
export const EDIT_ADMIN_REQUEST = "EDIT_ADMIN_REQUEST";

export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";
export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";

export const GET_DENTIST_ERROR = "GET_DENTIST_ERROR";
export const GET_DENTIST_REQUEST = "GET_DENTIST_REQUEST";
export const GET_DENTIST_SUCCESS = "GET_DENTIST_SUCCESS";

export const GET_ADMIN_ERROR = "GET_ADMIN_ERROR";
export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";

export const GET_DENTIST_PROFILE_ERROR = "GET_DENTIST_PROFILE_ERROR";
export const GET_DENTIST_PROFILE_REQUEST = "GET_DENTIST_PROFILE_REQUEST";
export const GET_DENTIST_PROFILE_SUCCESS = "GET_DENTIST_PROFILE_SUCCESS";

export const GET_PATIENT_PROFILE_ERROR = "GET_PATIENT_PROFILE_ERROR";
export const GET_PATIENT_PROFILE_REQUEST = "GET_PATIENT_PROFILE_REQUEST";
export const GET_PATIENT_PROFILE_SUCCESS = "GET_PATIENT_PROFILE_SUCCESS";

export const GET_ADMIN_PROFILE_ERROR = "GET_ADMIN_PROFILE_ERROR";
export const GET_ADMIN_PROFILE_REQUEST = "GET_ADMIN_PROFILE_REQUEST";
export const GET_ADMIN_PROFILE_SUCCESS = "GET_ADMIN_PROFILE_SUCCESS";

export const GET_ANKESAT_ERROR = "GET_ANKESAT_ERROR";
export const GET_ANKESAT_REQUEST = "GET_ANKESAT_REQUEST";
export const GET_ANKESAT_SUCCESS = "GET_ANKESAT_SUCCESS";

export const EDIT_ANKESAT_SUCCESS = "EDIT_ANKESAT_SUCCESS";
export const EDIT_ANKESAT_ERROR = "EDIT_ANKESAT_ERROR";
export const EDIT_ANKESAT_REQUEST = "EDIT_ANKESAT_REQUEST";

export const GET_DEPARTMENT_ERROR = "GET_DEPARTMENT_ERROR";
export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";

export const EDIT_DEPARTMENT_SUCCESS = "EDIT_DEPARTMENT_SUCCESS";
export const EDIT_DEPARTMENT_ERROR = "EDIT_DEPARTMENT_ERROR";
export const EDIT_DEPARTMENT_REQUEST = "EDIT_DEPARTMENT_REQUEST";

export const REGISTER_DEPARTMENT_SUCCESS = "REGISTER_DEPARTMENT_SUCCESS";
export const REGISTER_DEPARTMENT_ERROR = "REGISTER_DEPARTMENT_ERROR";
export const REGISTER_DEPARTMENT_REQUEST = "REGISTER_DEPARTMENT_REQUEST";

export const EDIT_INVENTARY_SUCCESS = "EDIT_INVENTARY_SUCCESS";
export const EDIT_INVENTARY_ERROR = "EDIT_INVENTARY_ERROR";
export const EDIT_INVENTARY_REQUEST = "EDIT_INVENTARY_REQUEST";

export const REGISTER_INVENTARY_SUCCESS = "REGISTER_INVENTARY_SUCCESS";
export const REGISTER_INVENTARY_ERROR = "REGISTER_INVENTARY_ERROR";
export const REGISTER_INVENTARY_REQUEST = "REGISTER_INVENTARY_REQUEST";

export const EDIT_KNOWLEDGE_SUCCESS = "EDIT_KNOWLEDGE_SUCCESS";
export const EDIT_KNOWLEDGE_ERROR = "EDIT_KNOWLEDGE_ERROR";
export const EDIT_KNOWLEDGE_REQUEST = "EDIT_KNOWLEDGE_REQUEST";

export const REGISTER_KNOWLEDGE_SUCCESS = "REGISTER_KNOWLEDGE_SUCCESS";
export const REGISTER_KNOWLEDGE_ERROR = "REGISTER_KNOWLEDGE_ERROR";
export const REGISTER_KNOWLEDGE_REQUEST = "REGISTER_KNOWLEDGE_REQUEST";

export const EDIT_MARKETING_SUCCESS = "EDIT_MARKETING_SUCCESS";
export const EDIT_MARKETING_ERROR = "EDIT_MARKETING_ERROR";
export const EDIT_MARKETING_REQUEST = "EDIT_MARKETING_REQUEST";

export const REGISTER_MARKETING_SUCCESS = "REGISTER_MARKETING_SUCCESS";
export const REGISTER_MARKETING_ERROR = "REGISTER_MARKETING_ERROR";
export const REGISTER_MARKETING_REQUEST = "REGISTER_MARKETING_REQUEST";

export const EDIT_MEDICALRECORD_SUCCESS = "EDIT_MEDICALRECORD_SUCCESS";
export const EDIT_MEDICALRECORD_ERROR = "EDIT_MEDICALRECORD_ERROR";
export const EDIT_MEDICALRECORD_REQUEST = "EDIT_MEDICALRECORD_REQUEST";

export const GET_MEDICALRECORD_ERROR = "GET_MEDICALRECORD_ERROR";
export const GET_MEDICALRECORD_REQUEST = "GET_MEDICALRECORD_REQUEST";
export const GET_MEDICALRECORD_SUCCESS = "GET_MEDICALRECORD_SUCCESS";

export const EDIT_PARTNER_SUCCESS = "EDIT_PARTNER_SUCCESS";
export const EDIT_PARTNER_ERROR = "EDIT_PARTNER_ERROR";
export const EDIT_PARTNER_REQUEST = "EDIT_PARTNER_REQUEST";

export const REGISTER_PARTNER_ERROR = "REGISTER_PARTNER_ERROR";
export const REGISTER_PARTNER_REQUEST = "REGISTER_PARTNER_REQUEST";
export const REGISTER_PARTNER_SUCCESS = "REGISTER_PARTNER_SUCCESS";

export const EDIT_PATIENTNOTE_SUCCESS = "EDIT_PATIENTNOTE_SUCCESS";
export const EDIT_PATIENTNOTE_ERROR = "EDIT_PATIENTNOTE_ERROR";
export const EDIT_PATIENTNOTE_REQUEST = "EDIT_PATIENTNOTE_REQUEST";

export const GET_PATIENTNOTE_ERROR = "GET_PATIENTNOTE_ERROR";
export const GET_PATIENTNOTE_REQUEST = "GET_PATIENTNOTE_REQUEST";
export const GET_PATIENTNOTE_SUCCESS = "GET_PATIENTNOTE_SUCCESS";

export const EDIT_PRESCRIPTION_SUCCESS = "EDIT_PRESCRIPTION_SUCCESS";
export const EDIT_PRESCRIPTION_ERROR = "EDIT_PRESCRIPTION_ERROR";
export const EDIT_PRESCRIPTION_REQUEST = "EDIT_PRESCRIPTION_REQUEST";

export const GET_PRESCRIPTION_ERROR = "GET_PRESCRIPTION_ERROR";
export const GET_PRESCRIPTION_REQUEST = "GET_PRESCRIPTION_REQUEST";
export const GET_PRESCRIPTION_SUCCESS = "GET_PRESCRIPTION_SUCCESS";

export const EDIT_TERAPIA_SUCCESS = "EDIT_TERAPIA_SUCCESS";
export const EDIT_TERAPIA_ERROR = "EDIT_TERAPIA_ERROR";
export const EDIT_TERAPIA_REQUEST = "EDIT_TERAPIA_REQUEST";

export const GET_TERAPIA_ERROR = "GET_TERAPIA_ERROR";
export const GET_TERAPIA_REQUEST = "GET_TERAPIA_REQUEST";
export const GET_TERAPIA_SUCCESS = "GET_TERAPIA_SUCCESS";

export const EDIT_TERMINET_SUCCESS = "EDIT_TERMINET_SUCCESS";
export const EDIT_TERMINET_ERROR = "EDIT_TERMINET_ERROR";
export const EDIT_TERMINET_REQUEST = "EDIT_TERMINET_REQUEST";

export const GET_TERMINET_ERROR = "GET_TERMINET_ERROR";
export const GET_TERMINET_REQUEST = "GET_TERMINET_REQUEST";
export const GET_TERMINET_SUCCESS = "GET_TERMINET_SUCCESS";

export const EDIT_VLERSIMET_SUCCESS = "EDIT_VLERSIMET_SUCCESS";
export const EDIT_VLERSIMET_ERROR = "EDIT_VLERSIMET_ERROR";
export const EDIT_VLERSIMET_REQUEST = "EDIT_VLERSIMET_REQUEST";

export const GET_VLERSIMET_ERROR = "GET_VLERSIMET_ERROR";
export const GET_VLERSIMET_REQUEST = "GET_VLERSIMET_REQUEST";
export const GET_VLERSIMET_SUCCESS = "GET_VLERSIMET_SUCCESS";

export const EDIT_SHERBIMESHTESE_SUCCESS = "EDIT_SHERBIMESHTESE_SUCCESS";
export const EDIT_SHERBIMESHTESE_ERROR = "EDIT_SHERBIMESHTESE_ERROR";
export const EDIT_SHERBIMESHTESE_REQUEST = "EDIT_SHERBIMESHTESE_REQUEST";

export const REGISTER_SHERBIMESHTESE_SUCCESS = "REGISTER_SHERBIMESHTESE_SUCCESS";
export const REGISTER_SHERBIMESHTESE_ERROR = "REGISTER_SHERBIMESHTESE_ERROR";
export const REGISTER_SHERBIMESHTESE_REQUEST = "REGISTER_SHERBIMESHTESE_REQUEST";