export const GET_DENTIST_SUCCESS = "GET_DENTIST_SUCCESS";
export const GET_DENTIST_ERROR = "GET_DENTIST_ERROR";
export const GET_DENTIST_REQUEST = "GET_DENTIST_REQUEST";

export const GET_PATIENT_SUCCESS = "GET_PATIENT_SUCCESS";
export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";

export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const GET_ADMIN_ERROR = "GET_ADMIN_ERROR";
export const GET_ADMIN_REQUEST = "GET_ADMIN_REQUEST";

export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const DELETE_ADMIN_ERROR = "DELETE_ADMIN_ERROR";
export const DELETE_ADMIN_REQUEST = "DELETE_ADMIN_REQUEST";

export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_ERROR = "DELETE_PATIENT_ERROR";
export const DELETE_PATIENT_REQUEST = "DELETE_PATIENT_REQUEST";

export const DELETE_DENTIST_SUCCESS = "DELETE_DENTIST_SUCCESS";
export const DELETE_DENTIST_ERROR = "DELETE_DENTIST_ERROR";
export const DELETE_DENTIST_REQUEST = "DELETE_DENTIST_REQUEST";

export const GET_ANKESAT_SUCCESS = "GET_ANKESAT_SUCCESS";
export const GET_ANKESAT_ERROR = "GET_ANKESAT_ERROR";
export const GET_ANKESAT_REQUEST = "GET_ANKESAT_REQUEST";

export const DELETE_ANKESAT_SUCCESS = "DELETE_ANKESAT_SUCCESS";
export const DELETE_ANKESAT_ERROR = "DELETE_ANKESAT_ERROR";
export const DELETE_ANKESAT_REQUEST = "DELETE_ANKESAT_REQUEST";

export const ADD_ANKESAT_SUCCESS = "ADD_ANKESAT_SUCCESS";
export const ADD_ANKESAT_ERROR = "ADD_ANKESAT_ERROR";
export const ADD_ANKESAT_REQUEST = "ADD_ANKESAT_REQUEST";

export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_ERROR = "GET_DEPARTMENT_ERROR";
export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";

export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_ERROR = "DELETE_DEPARTMENT_ERROR";
export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";

export const GET_INVENTARY_SUCCESS = "GET_INVENTARY_SUCCESS";
export const GET_INVENTARY_ERROR = "GET_INVENTARY_ERROR";
export const GET_INVENTARY_REQUEST = "GET_INVENTARY_REQUEST";

export const DELETE_INVENTARY_SUCCESS = "DELETE_INVENTARY_SUCCESS";
export const DELETE_INVENTARY_ERROR = "DELETE_INVENTARY_ERROR";
export const DELETE_INVENTARY_REQUEST = "DELETE_INVENTARY_REQUEST";

export const GET_KNOWLEDGE_SUCCESS = "GET_KNOWLEDGE_SUCCESS";
export const GET_KNOWLEDGE_ERROR = "GET_KNOWLEDGE_ERROR";
export const GET_KNOWLEDGE_REQUEST = "GET_KNOWLEDGE_REQUEST";

export const DELETE_KNOWLEDGE_SUCCESS = "DELETE_KNOWLEDGE_SUCCESS";
export const DELETE_KNOWLEDGE_ERROR = "DELETE_KNOWLEDGE_ERROR";
export const DELETE_KNOWLEDGE_REQUEST = "DELETE_KNOWLEDGE_REQUEST";

export const GET_MARKETING_SUCCESS = "GET_MARKETING_SUCCESS";
export const GET_MARKETING_ERROR = "GET_MARKETING_ERROR";
export const GET_MARKETING_REQUEST = "GET_MARKETING_REQUEST";

export const DELETE_MARKETING_SUCCESS = "DELETE_MARKETING_SUCCESS";
export const DELETE_MARKETING_ERROR = "DELETE_MARKETING_ERROR";
export const DELETE_MARKETING_REQUEST = "DELETE_MARKETING_REQUEST";

export const GET_MEDICALRECORD_SUCCESS = "GET_MEDICALRECORD_SUCCESS";
export const GET_MEDICALRECORD_ERROR = "GET_MEDICALRECORD_ERROR";
export const GET_MEDICALRECORD_REQUEST = "GET_MEDICALRECORD_REQUEST";

export const DELETE_MEDICALRECORD_SUCCESS = "DELETE_MEDICALRECORD_SUCCESS";
export const DELETE_MEDICALRECORD_ERROR = "DELETE_MEDICALRECORD_ERROR";
export const DELETE_MEDICALRECORD_REQUEST = "DELETE_MEDICALRECORD_REQUEST";

export const ADD_MEDICALRECORD_SUCCESS = "ADD_MEDICALRECORD_SUCCESS";
export const ADD_MEDICALRECORD_ERROR = "ADD_MEDICALRECORD_ERROR";
export const ADD_MEDICALRECORD_REQUEST = "ADD_MEDICALRECORD_REQUEST";

export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS";
export const GET_PARTNER_ERROR = "GET_PARTNER_ERROR";
export const GET_PARTNER_REQUEST = "GET_PARTNER_REQUEST";

export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_ERROR = "DELETE_PARTNER_ERROR";
export const DELETE_PARTNER_REQUEST = "DELETE_PARTNER_REQUEST";

export const GET_PATIENTNOTE_SUCCESS = "GET_PATIENTNOTE_SUCCESS";
export const GET_PATIENTNOTE_ERROR = "GET_PATIENTNOTE_ERROR";
export const GET_PATIENTNOTE_REQUEST = "GET_PATIENTNOTE_REQUEST";

export const DELETE_PATIENTNOTE_SUCCESS = "DELETE_PATIENTNOTE_SUCCESS";
export const DELETE_PATIENTNOTE_ERROR = "DELETE_PATIENTNOTE_ERROR";
export const DELETE_PATIENTNOTE_REQUEST = "DELETE_PATIENTNOTE_REQUEST";

export const ADD_PATIENTNOTE_SUCCESS = "ADD_PATIENTNOTE_SUCCESS";
export const ADD_PATIENTNOTE_ERROR = "ADD_PATIENTNOTE_ERROR";
export const ADD_PATIENTNOTE_REQUEST = "ADD_PATIENTNOTE_REQUEST";

export const GET_PRESCRIPTION_SUCCESS = "GET_PRESCRIPTION_SUCCESS";
export const GET_PRESCRIPTION_ERROR = "GET_PRESCRIPTION_ERROR";
export const GET_PRESCRIPTION_REQUEST = "GET_PRESCRIPTION_REQUEST";

export const DELETE_PRESCRIPTION_SUCCESS = "DELETE_PRESCRIPTION_SUCCESS";
export const DELETE_PRESCRIPTION_ERROR = "DELETE_PRESCRIPTION_ERROR";
export const DELETE_PRESCRIPTION_REQUEST = "DELETE_PRESCRIPTION_REQUEST";

export const ADD_PRESCRIPTION_SUCCESS = "ADD_PRESCRIPTION_SUCCESS";
export const ADD_PRESCRIPTION_ERROR = "ADD_PRESCRIPTION_ERROR";
export const ADD_PRESCRIPTION_REQUEST = "ADD_PRESCRIPTION_REQUEST";

export const GET_SHERBIMESHTESE_SUCCESS = "GET_SHERBIMESHTESE_SUCCESS";
export const GET_SHERBIMESHTESE_ERROR = "GET_SHERBIMESHTESE_ERROR";
export const GET_SHERBIMESHTESE_REQUEST = "GET_SHERBIMESHTESE_REQUEST";

export const DELETE_SHERBIMESHTESE_SUCCESS = "DELETE_SHERBIMESHTESE_SUCCESS";
export const DELETE_SHERBIMESHTESE_ERROR = "DELETE_SHERBIMESHTESE_ERROR";
export const DELETE_SHERBIMESHTESE_REQUEST = "DELETE_SHERBIMESHTESE_REQUEST";

export const GET_TERAPIA_SUCCESS = "GET_TERAPIA_SUCCESS";
export const GET_TERAPIA_ERROR = "GET_TERAPIA_ERROR";
export const GET_TERAPIA_REQUEST = "GET_TERAPIA_REQUEST";

export const DELETE_TERAPIA_SUCCESS = "DELETE_TERAPIA_SUCCESS";
export const DELETE_TERAPIA_ERROR = "DELETE_TERAPIA_ERROR";
export const DELETE_TERAPIA_REQUEST = "DELETE_TERAPIA_REQUEST";

export const ADD_TERAPIA_SUCCESS = "ADD_TERAPIA_SUCCESS";
export const ADD_TERAPIA_ERROR = "ADD_TERAPIA_ERROR";
export const ADD_TERAPIA_REQUEST = "ADD_TERAPIA_REQUEST";

export const GET_TERMINET_SUCCESS = "GET_TERMINET_SUCCESS";
export const GET_TERMINET_ERROR = "GET_TERMINET_ERROR";
export const GET_TERMINET_REQUEST = "GET_TERMINET_REQUEST";

export const DELETE_TERMINET_SUCCESS = "DELETE_TERMINET_SUCCESS";
export const DELETE_TERMINET_ERROR = "DELETE_TERMINET_ERROR";
export const DELETE_TERMINET_REQUEST = "DELETE_TERMINET_REQUEST";

export const ADD_TERMINET_SUCCESS = "ADD_TERMINET_SUCCESS";
export const ADD_TERMINET_ERROR = "ADD_TERMINET_ERROR";
export const ADD_TERMINET_REQUEST = "ADD_TERMINET_REQUEST";

export const GET_VLERSIMET_SUCCESS = "GET_VLERSIMET_SUCCESS";
export const GET_VLERSIMET_ERROR = "GET_VLERSIMET_ERROR";
export const GET_VLERSIMET_REQUEST = "GET_VLERSIMET_REQUEST";

export const DELETE_VLERSIMET_SUCCESS = "DELETE_VLERSIMET_SUCCESS";
export const DELETE_VLERSIMET_ERROR = "DELETE_VLERSIMET_ERROR";
export const DELETE_VLERSIMET_REQUEST = "DELETE_VLERSIMET_REQUEST";

export const ADD_VLERSIMET_SUCCESS = "ADD_VLERSIMET_SUCCESS";
export const ADD_VLERSIMET_ERROR = "ADD_VLERSIMET_ERROR";
export const ADD_VLERSIMET_REQUEST = "ADD_VLERSIMET_REQUEST";